export const common={
    divInfo:[
        {
            level:0,
            color:"white",
            bgColor:"black"
        },
        {
            level:1,
            color:"white",
            bgColor:"#2e8a73"
        },
        {
            level:2,
            color:"white",
            bgColor:"#3db497"
        },
        {
            level:3,
            color:"white",
            bgColor:"#37a58a"
        },
        {
            level:4,
            color:"white",
            bgColor:"#2e8a73"
        },
        {
            level:5,
            color:"white",
            bgColor:"#27725f"
        },
        {
            level:6,
            color:"white",
            bgColor:"#1f5e4e"
        },
        {
            level:7,
            color:"white",
            bgColor:"#216151"
        },
        {
            level:8,
            color:"white",
            bgColor:"#163f35"
        },
        {
            level:9,
            color:"white",
            bgColor:"#0b1f1a"
        },
        {
            level:10,
            color:"white",
            bgColor:"#030807"
        },
    ]
}